name: zip_file

on:
  push:
    branches: [main]
jobs:
  build-zip:
    name: zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: zip
        uses: thedoctor0/zip-release@master
        with:
          filename: 'CancelCaveSound.zip'
          path: 'data LICENSE pack.mcmeta'

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: action-zip-release
          path: 'CancelCaveSound.zip'